spring.application.name=GraficasOTRS

#nombre del servidor
server.port=8080
server.serevlet.context-path=/


#directorios de almacenamiento
app.upload.dir=uploads/
app.pdf.dir=pdfs/
app.logo.dir=classpath:logo/

#emails fijos que se mostraran en el pdf

app.emails.fijos=mauricio.sanchez@palotinto.com,adrian.gomez@palotinto.com,\
  david.perez@palotinto.com,daniel.antonio@palotinto.com,\
  jacqueline.garcia@palotinto.com,omar.varela@palotinto.com, angelica.yanez@palotinto.com, rodrigoh@palotinto.com

#configuracion de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#logging
logging.level.com.palotinto.tickets=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n